name: Cache Collection

on: 
  push:
  workflow_dispatch:

jobs:
  collect:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     group: [1,2]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # curl -sSf https://lets.tunshell.com/init.sh | sh -s -- T Z19QDAcipLmvS1hhqHC5Dh OeBaLQX0yCnZKHfLBOkulG
          python ./script/split_tests.py 2 tests
      - name: Upload pytest_buckets
        uses: actions/upload-artifact@v4.3.3
        with:
          name: pytest_buckets
          path: pytest_buckets.txt
          overwrite: true
      # - name: Run pytest
      #   run: pytest --cov --splits 5 --group ${{ matrix.group }}
      # - name: Upload coverage
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: coverage${{ matrix.group }}
      #     path: .coverage

  test:
    needs: collect
    runs-on: ubuntu-latest
    strategy:
      matrix:
        group: [1,2]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Download all artifacts
        # Downloads coverage1, coverage2, etc.
        uses: actions/download-artifact@v2
      - name: Run Tests
        run: |
           pytest \
            $(sed -n "${{ matrix.group }},1p" pytest_buckets.txt) \
              2>&1 | tee pytest-${{ matrix.group }}.txt
      # - name: Run coverage
      #   run: |
      #     coverage combine coverage*/.coverage*
      #     coverage report --fail-under=100
      #     coverage xml
      # - uses: codecov/codecov-action@v1



      # this was from home-assistant using the output from pytest
      
      #  - name: Upload pytest output
      #   if: success() || failure() && steps.pytest-full.conclusion == 'failure'
      #   uses: actions/upload-artifact@v4.3.3
      #   with:
      #     name: pytest-${{ github.run_number }}-${{ matrix.python-version }}-${{ matrix.group }}
      #     path: pytest-*.txt
      #     overwrite: true
      # - name: Upload coverage artifact
      #   if: needs.info.outputs.skip_coverage != 'true'
      #   uses: actions/upload-artifact@v4.3.3
      #   with:
      #     name: coverage-${{ matrix.python-version }}-${{ matrix.group }}
      #     path: coverage.xml
      #     overwrite: true
