name: Test Actions

on: 
  # push: # may need something like this for push events ${{ github.event.inputs.groups || 2 }}
  workflow_dispatch:
    inputs:
      groups:
        description: "Number of groups"
        default: 2
        type: number

jobs:
  collect:
    runs-on: ubuntu-latest

    outputs:
      outputmatrix: ${{ steps.splittests.outputs.outputmatrix }}
    
    steps:
      - uses: actions/checkout@v2
      - id: splittests
        uses: hosted-runners-perf/action-python-test-split@v0.0.2
        with:
          groups: ${{ inputs.groups }}

  test:
    needs: collect
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.collect.outputs.outputmatrix) }}
    steps:
      - uses: actions/checkout@v2
      - id: runtests
        uses: hosted-runners-perf/action-python-test-runner@v0.0.1
        with:
          group: ${{ matrix.group }}
